version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta padrão do RabbitMQ para comunicação
      - "15672:15672" # Porta para acessar o RabbitMQ Management (interface web)
    environment:
      RABBITMQ_DEFAULT_USER: admin   # Usuário padrão
      RABBITMQ_DEFAULT_PASS: admin   # Senha padrão
